#ifndef DEFINITIONS_H
#define DEFINITIONS_H
#define BLE_ADVERT_MAX_LEN 31

#define MAX_LENGTH_SHORT_NAME 10
#define MAX_LENGTH_COMPLETE_NAME 20

#define FLAG 0x020106
#define FLAG1 0x02
#define FLAG2 0x01
#define FLAG3 0x06
#define UUID 0xD2FC
#define UUID1 0xD2
#define UUID2 0xFC
#define SERVICE_DATA 0x16

#define NO_ENCRYPT 0x40
#define NO_ENCRYPT_TRIGGER_BASE 0x44
#define ENCRYPT 0x41
#define ENCRYPT_TRIGGER_BASE 0x45

#define SHORT_NAME 0x08
#define COMPLETE_NAME 0x09

#define EVENT_BUTTON 0x3A
#define EVENT_BUTTON_NONE 0x00
#define EVENT_BUTTON_PRESS 0x01
#define EVENT_BUTTON_DOUBLE_PRESS 0x02
#define EVENT_BUTTON_TRIPLE_PRESS 0x03
#define EVENT_BUTTON_LONG_PRESS 0x04
#define EVENT_BUTTON_LONG_DOUBLE_PRESS 0x05
#define EVENT_BUTTTON_LONG_TRIPLE_PRESS 0x06

#define EVENT_DIMMER 0x3C
#define EVENT_DIMMER_NONE 0x00
#define EVENT_DIMMER_LEFT 0x01
#define EVENT_DIMMER_RIGHT 0x02

#endif