#ifndef DEFINITIONS_H
#define DEFINITIONS_H
#define BLE_ADVERT_MAX_LEN 31

#define MAX_LENGTH_SHORT_NAME 10
#define MAX_LENGTH_COMPLETE_NAME 20

#define FLAG 0x020106
#define FLAG1 0x02
#define FLAG2 0x01
#define FLAG3 0x06
#define UUID 0xD2FC
#define UUID1 0xD2
#define UUID2 0xFC
#define SERVICE_DATA 0x16

#define NO_ENCRYPT 0x40
#define NO_ENCRYPT_TRIGGER_BASE 0x44
#define ENCRYPT 0x41
#define ENCRYPT_TRIGGER_BASE 0x45

#define SHORT_NAME 0x08
#define COMPLETE_NAME 0x09


#define STATE_BATTERY_LOW 0x15
#define STATE_BATTERY_CHARHING 0x16
#define STATE_CO 0x17
#define STATE_COLD 0x18
#define STATE_CONNECTIVITY 0x19
#define STATE_DOOR 0x1A
#define STATE_GARAGE_DOOR 0x1B
#define STATE_GAS_DETECTED 0x1C
#define STATE_GENERIC_BOOLEAN 0x0F
#define STATE_HEAT 0x1D
#define STATE_LIGHT 0x1E
#define STATE_LOCK 0x1F
#define STATE_MOISTURE 0x20
#define STATE_MOTION 0x21
#define STATE_MOVING 0x22
#define STATE_OCCUPANCY 0x23
#define STATE_OPENING 0x11
#define STATE_PLUG 0x24
#define STATE_POWER_ON 0x10
#define STATE_PRESENCE 0x25
#define STATE_PROBLEM 0x26
#define STATE_RUNNING 0x27
#define STATE_SAFETY 0x28
#define STATE_SMOKE 0x29
#define STATE_SOUND 0x2A
#define STATE_TAMPER 0x2B
#define STATE_VIBRATION 0x2C
#define STATE_WINDOW 0x2D

#define STATE_ON 0x01
#define STATE_OFF 0x00

#define EVENT_BUTTON 0x3A
#define EVENT_BUTTON_NONE 0x00
#define EVENT_BUTTON_PRESS 0x01
#define EVENT_BUTTON_DOUBLE_PRESS 0x02
#define EVENT_BUTTON_TRIPLE_PRESS 0x03
#define EVENT_BUTTON_LONG_PRESS 0x04
#define EVENT_BUTTON_LONG_DOUBLE_PRESS 0x05
#define EVENT_BUTTTON_LONG_TRIPLE_PRESS 0x06

#define EVENT_DIMMER 0x3C
#define EVENT_DIMMER_NONE 0x00
#define EVENT_DIMMER_LEFT 0x01
#define EVENT_DIMMER_RIGHT 0x02

#endif